# Generated by Django 4.0.5 on 2022-06-07 03:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofposts', models.IntegerField(default=0)),
                ('title', models.CharField(default='A category', max_length=100)),
                ('description', models.CharField(default='The description of a category.', max_length=100)),
                ('icon', models.URLField(default='https://uxwing.com/wp-content/themes/uxwing/download/03-editing-user-action/three-horizontal-lines.png')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='This is an empty comment.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadlink', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=75)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(default='#333333', max_length=9)),
                ('numberofusers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('userbio', models.CharField(default='This user has not modified his bio.', max_length=500)),
                ('userupvotes', models.IntegerField(default=0)),
                ('userpfp', models.URLField(default='https://i.pinimg.com/736x/c9/e3/e8/c9e3e810a8066b885ca4e882460785fa.jpg')),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=100)),
                ('banned', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.userrole')),
                ('userposts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='downloads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.download'),
        ),
        migrations.AddField(
            model_name='post',
            name='postcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.post'),
        ),
    ]
