# Generated by Django 4.0.5 on 2022-06-07 10:59

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdat',
            field=models.BigIntegerField(default=time.time),
        ),
        migrations.AddField(
            model_name='post',
            name='createdat',
            field=models.BigIntegerField(default=time.time),
        ),
        migrations.AddField(
            model_name='user',
            name='createdat',
            field=models.BigIntegerField(default=time.time),
        ),
    ]
