# Generated by Django 3.2.13 on 2022-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0002_comment_createdat_post_createdat_user_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(default='255.255.255.255'),
        ),
    ]
