# Generated by Django 3.2.13 on 2022-06-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0003_auto_20220607_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userposts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.post'),
        ),
    ]
