# Generated by Django 3.2.13 on 2022-06-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0004_alter_user_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='downloads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.download'),
        ),
    ]
