# Generated by Django 3.2.13 on 2022-06-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0005_auto_20220607_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SerenityForum.comment'),
        ),
    ]
