# Generated by Django 4.0.5 on 2022-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0006_alter_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
