# Generated by Django 3.2.13 on 2022-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0007_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('reservationkey', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
