# Generated by Django 3.2.13 on 2022-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerenityForum', '0008_reservedusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedusername',
            name='reservationkey',
            field=models.CharField(max_length=25),
        ),
    ]
